# -*- coding: utf8 -*-
from cwmm_constants import *
from header_operations import *
from header_common import *
from header_triggers import *

cwmm_triggers = [

    (ti_on_agent_killed_or_wounded, 0, 0, [(multiplayer_is_dedicated_server),(eq, "$g_cwmm_server_is_in_match", 1)], [
        (store_trigger_param_1, ":dead_agent_no"), 
        (store_trigger_param_2, ":killer_agent_no"),

        (assign, ":dead_player_no", -1),
        (assign, ":killer_player_no", -1),

        (try_begin),
            (agent_is_active, ":dead_agent_no"),
            (agent_get_player_id, ":dead_player_no", ":dead_agent_no"),
        (try_end),

        (try_begin),
            (agent_is_active, ":killer_agent_no"),
            (agent_get_player_id, ":killer_player_no", ":killer_agent_no"),
        (try_end),

        (try_begin),
            (player_is_active, ":dead_player_no"),
            (call_script, "script_cwmm_add_player_stat", ":dead_player_no", INDEX_DEATH, 1),
        (try_end),

        (try_begin),
            (player_is_active, ":killer_player_no"),
            (player_is_active, ":dead_player_no"),
            (neq, ":dead_player_no", ":killer_player_no"),
            (player_get_team_no, ":killer_team_no", ":killer_player_no"),
            (player_get_team_no, ":dead_team_no", ":dead_player_no"),
            (is_between, ":killer_team_no", 0, 2),
            (is_between, ":dead_team_no", 0, 2),
            (try_begin),
                (eq, ":killer_team_no", ":dead_team_no"),
                (call_script, "script_cwmm_add_player_stat", ":killer_player_no", INDEX_TEAM_KILL, 1),
            (else_try),
                (call_script, "script_cwmm_add_player_stat", ":killer_player_no", INDEX_KILL, 1),
            (try_end),
        (try_end),

    ]),

    (ti_on_agent_hit, 0, 0, [(multiplayer_is_dedicated_server),(eq, "$g_cwmm_server_is_in_match", 1)], [
        (store_trigger_param_1, ":receiver_agent_no"), 
        (store_trigger_param_2, ":attacker_agent_no"),
        (store_trigger_param_3, ":damage"),

        (store_agent_hit_points, ":hp", ":receiver_agent_no", 1),
        (val_min, ":damage", ":hp"),
        (gt, ":damage", 0),

        (assign, ":receiver_player_no", -1),
        (assign, ":attacker_player_no", -1),

        (try_begin),
            (agent_is_active, ":receiver_agent_no"),
            (agent_is_human, ":receiver_agent_no"),
            (agent_get_player_id, ":receiver_player_no", ":receiver_agent_no"),
        (try_end),

        (try_begin),
            (agent_is_active, ":attacker_agent_no"),
            (try_begin),
                (agent_is_human, ":attacker_agent_no"),
                (agent_get_player_id, ":attacker_player_no", ":attacker_agent_no"),
            (else_try),
                (agent_get_rider, ":attacker_rider_agent_no", ":attacker_agent_no"),
                (agent_is_active, ":attacker_rider_agent_no"),
                (agent_get_player_id, ":attacker_player_no", ":attacker_rider_agent_no"),
            (try_end),
        (try_end),

        (player_is_active, ":receiver_player_no"),
        (player_is_active, ":attacker_player_no"),
        (neq, ":receiver_player_no", ":attacker_player_no"),
        (player_get_team_no, ":receiver_team_no", ":receiver_player_no"),
        (player_get_team_no, ":attacker_team_no", ":attacker_player_no"),
        (is_between, ":receiver_team_no", 0, 2),
        (is_between, ":attacker_team_no", 0, 2),
        (try_begin),
            (eq, ":receiver_team_no", ":attacker_team_no"),
            (call_script, "script_cwmm_add_player_stat", ":attacker_player_no", INDEX_TEAM_DAMAGE, ":damage"),
            (call_script, "script_cwmm_add_player_stat", ":attacker_player_no", INDEX_TEAM_HIT, 1),
        (else_try),
            (call_script, "script_cwmm_add_player_stat", ":attacker_player_no", INDEX_DAMAGE, ":damage"),
            (call_script, "script_cwmm_add_player_stat", ":attacker_player_no", INDEX_HIT, 1),
        (try_end),

    ]),

    (1, 0, 0, [(multiplayer_is_dedicated_server)], [
        (try_begin),
            (le, "$g_cwmm_next_tick_seconds", 0),
            (call_script, "script_cwmm_server_tick"),
            (assign, "$g_cwmm_next_tick_seconds", CWMM_DEFAULT_TICK_INTERVAL),
        (else_try),
            (val_sub, "$g_cwmm_next_tick_seconds", 1),
        (try_end),
    ]),

    # 当服务器没有人时，触发器的执行间隔会拉长，借此实现保底Tick
    (0.3, 0, 0, [(multiplayer_is_dedicated_server)], [
        (assign, ":num_players", 0),
        (try_for_players, ":player_no"),
            (player_is_active, ":player_no"),
            (val_add, ":num_players", 1),
        (try_end),
        (try_begin),
            (eq, ":num_players", 0),
            (call_script, "script_cwmm_server_tick"),
        (try_end),
    ]),

    (ti_server_player_joined, 0, 0, [(multiplayer_is_dedicated_server)], [
        (store_trigger_param_1, ":player_no"),

        (player_set_slot, ":player_no", slot_player_allowed_team, -1),
        (player_set_slot, ":player_no", slot_player_not_allowed_team_counter, 0),

        (player_get_unique_id, reg11, ":player_no"),
        (assign, reg12, ":player_no"),
        (str_store_player_username, s9, ":player_no"),
        (str_store_server_name, s10),
        (send_message_to_url, "str_cwmm_api_player_join"),

    ]),

    # 检测取消比赛和准备倒计时的触发器
    (1, 0, 0, [], [
        (multiplayer_is_server),
        (eq, "$g_cwmm_server_is_in_match", 1),
        (call_script,"script_cwmm_check_team_switch"),
        (try_begin),
            (eq, "$g_cwmm_server_is_waiting_for_players", 1),
            (assign, ":num_players", 0),
            (try_for_players, ":player_no"),
                (player_is_active, ":player_no"),
                (player_get_slot, ":allowed_team", ":player_no", slot_player_allowed_team),
                (is_between, ":allowed_team", 0, 2),
                (val_add, ":num_players", 1),
            (try_end),
            (store_mul, ":target_num_players", "$g_cwmm_team_size", 2),

            (try_begin),
                (ge, "$g_cwmm_wait_time_seconds", 0),
                (eq, ":num_players", ":target_num_players"),
                (assign, "$g_cwmm_server_is_waiting_for_players", 0),
                (assign, "$g_cwmm_match_countdown", CWMM_MATCH_START_COUNDOWN),
            (else_try),
                (val_sub, "$g_cwmm_wait_time_seconds", 1),
                (try_begin),
                    (lt, "$g_cwmm_wait_time_seconds", 0),
                    (call_script, "script_cwmm_set_should_cancel_match"),
                (else_try),
                    (store_mod, ":value", "$g_cwmm_wait_time_seconds", 5),
                    (this_or_next|eq, ":value", 0),
                    (le, "$g_cwmm_wait_time_seconds", 10),
                    (assign, reg11, "$g_cwmm_wait_time_seconds"),
                    (assign, reg12, ":num_players"),
                    (assign, reg13, ":target_num_players"),
                    (str_store_string, s1, "str_cwmm_reg11_seconds_wait_reg12_reg13"),
                    #(display_message, s1),
                    (call_script, "script_adimi_tool_server_message"),
                (try_end),
            (try_end),
        (else_try),
            (eq, "$g_cwmm_server_is_waiting_for_players", 0),
            (try_begin),
                (val_sub, "$g_cwmm_match_countdown", 1),
                (ge, "$g_cwmm_match_countdown", 0),

                (store_mod, ":countdown_mod", "$g_cwmm_match_countdown", 5),
                (try_begin),
                    (this_or_next|eq, ":countdown_mod", 0),
                    (le, "$g_cwmm_match_countdown", 10),
                    (assign, reg14, "$g_cwmm_match_countdown"),
                    (str_store_string, s1, "str_cwmm_start_countdown_reg14"),
                    (call_script, "script_adimi_tool_server_message"),
                (try_end),
            (try_end),
        (try_end),

        (try_begin),
            (this_or_next|eq, "$g_cwmm_server_is_waiting_for_players", 1),
            (ge, "$g_cwmm_match_countdown", 0),
            (store_mission_timer_a, "$g_round_start_time"),
            (try_for_players, ":player_no"),
                (player_is_active, ":player_no"),
                (multiplayer_send_int_to_player, ":player_no", multiplayer_event_set_round_start_time, -9999),
            (try_end),
        (try_end),

        (try_begin),
            (eq, "$g_cwmm_should_cancel_match", 1),
            # 需要记录所有已到场玩家的GUID
            (str_clear, s9),
            (try_for_players, ":player_no"),
                (player_is_active, ":player_no"),
                (player_get_unique_id, reg21, ":player_no"),
                (str_store_string, s9, "@{s9},{reg21}"),
            (try_end),
            (str_store_substring, s10, s9, 1),
            (str_store_server_name, s11),
            (send_message_to_url, "str_cwmm_api_cancel_match"),
        (else_try),
            (eq, "$g_cwmm_should_finish_match", 1),
            # 需要记录比分、所有玩家的Kill Death Damage Team_Damage
            (str_clear, s9),
            (try_for_range, ":index_no", 0, "$cwmm_next_data_index"),
                (try_for_range, ":sub_index_no", 0, CWMM_DATA_ARRAY_SLOTS),
                    (array_get_val, reg21, "$cwmm_data_array", ":index_no", ":sub_index_no"),
                    (str_store_string, s9, "@{s9},{reg21}"),
                (try_end),
            (try_end),
            (assign, reg11, "$g_cwmm_team_1_score"),
            (assign, reg12, "$g_cwmm_team_2_score"),
            (str_store_substring, s10, s9, 1),
            (str_store_server_name, s11),
            (send_message_to_url, "str_cwmm_api_finish_match"),
        (try_end),

    ]),

]